/* Generated by `npm run gen:api` (openapi-typescript) against the engine's
   /v3/api-docs. This committed snapshot keeps build/CI engine-independent.
   Regenerate after backend API changes. Minimal hand-seeded version below. */
export interface paths {
  '/baas/v1/customers': {
    get: {
      parameters: { query?: { page?: number; size?: number; sort?: string } };
      responses: {
        200: { content: { 'application/json': unknown } };
      };
    };
  };
}
export type webhooks = Record<string, never>;
export interface components { schemas: Record<string, never> }
export type operations = Record<string, never>;
