/* Generated by `npm run gen:api` (openapi-typescript) against the engine's
   /v3/api-docs. This committed snapshot keeps build/CI engine-independent.
   Regenerate after backend API changes. Minimal hand-seeded version below. */
export interface paths {
  '/baas/v1/customers': {
    get: {
      parameters: { query?: { page?: number; size?: number; sort?: string; kycStatus?: string; search?: string } };
      responses: {
        200: { content: { 'application/json': unknown } };
      };
    };
    post: {
      requestBody: { content: { 'application/json': unknown } };
      responses: {
        200: { content: { 'application/json': unknown } };
      };
    };
  };
  '/baas/v1/customers/{id}': {
    get: {
      parameters: { path: { id: string } };
      responses: {
        200: { content: { 'application/json': unknown } };
      };
    };
    put: {
      parameters: { path: { id: string } };
      requestBody: { content: { 'application/json': unknown } };
      responses: {
        200: { content: { 'application/json': unknown } };
      };
    };
  };
  '/baas/v1/customers/{id}/kyc-events': {
    get: {
      parameters: { path: { id: string } };
      responses: {
        200: { content: { 'application/json': unknown } };
      };
    };
  };
  '/baas/v1/customers/{id}/activate': {
    post: {
      parameters: { path: { id: string } };
      requestBody: { content: { 'application/json': unknown } };
      responses: {
        200: { content: { 'application/json': unknown } };
      };
    };
  };
  '/baas/v1/customers/{id}/suspend': {
    post: {
      parameters: { path: { id: string } };
      requestBody: { content: { 'application/json': unknown } };
      responses: {
        200: { content: { 'application/json': unknown } };
      };
    };
  };
  '/baas/v1/customers/{id}/reactivate': {
    post: {
      parameters: { path: { id: string } };
      requestBody: { content: { 'application/json': unknown } };
      responses: {
        200: { content: { 'application/json': unknown } };
      };
    };
  };
  '/baas/v1/customers/{id}/close': {
    post: {
      parameters: { path: { id: string } };
      requestBody: { content: { 'application/json': unknown } };
      responses: {
        200: { content: { 'application/json': unknown } };
      };
    };
  };
  '/baas/v1/dashboard/summary': {
    get: {
      responses: {
        200: { content: { 'application/json': unknown } };
      };
    };
  };
  '/baas/v1/operators/me': {
    get: {
      responses: {
        200: { content: { 'application/json': unknown } };
      };
    };
  };
}
export type webhooks = Record<string, never>;
export interface components { schemas: Record<string, never> }
export type operations = Record<string, never>;
